services:
  backend:
    build:
      context: ./pokemon_gashapon_backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=12345678
      - DATABASE_NAME=ct648
      - DATABASE_PORT=5432
      - PATH=/root/.bun/bin:$PATH
    depends_on:
      - db
    restart: always
    networks:
      - default

  frontend:
    build:
      context: ./pokemon_gashapon_front
    ports:
      - "80:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3001
    restart: always
    networks:
      - default

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=ct648
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
